poster/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tik.urls')),

] 

tik/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_us, name='login'),
    path('upload/', views.upload, name='upload'),
    path('homme/', views.homme, name='homme'),
    path('femme/', views.femme, name='femme'),
    path('logout/', views.logout_user, name='logout'),
    path('edit/<int:my_id>/', views.editform, name='update'),
    #path('download/', views.some_view, name='download_file'),
     path('demandeur/', views.demander, name='demandeur'),
     path('staf/', views.staf, name='staf'),
     path('donnees/', views.donne, name='donnee'),
     path('download/', views.download),
     path('detail/<int:id>/', views.detail, name='show'),
     path('modifier/<int:id>/', views.updatedemande, name='udm'),
     path('post_comment/<int:id>/', views.detail_post, name='post'),



     #path('rap/', views.rap, name='rap'),










]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tik/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    is_homme = models.BooleanField('Is_homme', default=False)
    is_femme = models.BooleanField('Is_femme', default=False)








class Postes(models.Model):
    autheur = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    titre = models.CharField(max_length=50)
    date_joind = models.DateTimeField(auto_now_add=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    desc = models.TextField()



    def __str__(self):
        return self.titre

class Comment(models.Model):
  post = models.ForeignKey(Postes, on_delete = models.CASCADE, related_name ='comments')
  user = models.ForeignKey(User, on_delete = models.CASCADE)
  content = models.TextField()
  def __str__(self):
    return self.post.titre
class Demandeur(models.Model):
    nom_tribunal = models.CharField(max_length=60)
    numero_dossier = models.CharField(max_length=20)
    date_jugement = models.DateField(auto_now=True)


    nom_president = models.CharField(max_length=60)
    nom_demandeure = models.CharField(max_length=60)
    nom_avocat1 = models.CharField(max_length=60)
    nom = models.CharField(max_length=60)
    local1 = models.CharField(max_length=60)
    nom_demande = models.CharField(max_length=60)
    nom_avocat2 = models.CharField(max_length=60)
    local2 = models.CharField(max_length=60)
    nom_notaire = models.CharField(max_length=60)
    date_invitation = models.DateTimeField(auto_now=True)
    num_inivation = models.CharField(max_length=60)
    vehicul_type = models.CharField(max_length=60)
    matricule = models.CharField(max_length=60)
    date_accident = models.DateTimeField(auto_now=True)
    lieu_accident = models.CharField(max_length=80)
    nom_proces = models.CharField(max_length=60)
    date_pv =models.DateTimeField(auto_now_add=True)
    source_pv = models.CharField(max_length=60)
    description_acc = models.TextField()
    num_ordonance = models.CharField(max_length=60)
    date_ordonance = models.DateField(auto_now_add=True)
    type_vehicule = models.CharField(max_length=60)
    date_expertise = models.DateField(auto_now=True)
    dmg_materiel = models.CharField(max_length=100)
    numero_dossier = models.CharField(max_length=60)
    nom_avocat1 = models.CharField(max_length=60)
    nom_avocat2 = models.CharField(max_length=60)
    date_pledorie = models.DateField(auto_now_add=True)
    nom_avocat = models.CharField(max_length=60)
    nom_avocatdeux = models.CharField(max_length=60)
    adminupload = models.FileField(upload_to='media')

    cout_expertise = models.CharField(max_length=60)
    honaire_avocat_demande = models.CharField(max_length=60)
    cout_invitation = models.CharField(max_length=60)
    avocat_honoraire_ordonnance_demandes = models.CharField(max_length=60)
    avocat_honoraire_ordonnance_juge = models.CharField(max_length=60)
    cout_information_expertise = models.CharField(max_length=60)
    Demande_contradictoire = models.CharField(max_length=60)

    période_assurance = models.CharField(max_length=60)



    def __str__(self):
        return self.nom

tik/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model

from .models import Postes, User, Demandeur, Comment



class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2', 'is_homme', 'is_femme')



class LoginForm(forms.Form):
    username = forms.CharField(max_length=63, label="nom d'utilisateur", help_text="Champ Obligatoire")
    password = forms.CharField(max_length=63, label="mot de passe", widget=forms.PasswordInput)



class PosteForm(forms.ModelForm):
    class Meta:
        model = Postes
        fields = '__all__'

class DemanderForm(forms.ModelForm):
    class Meta:
        model = Demandeur
        fields = '__all__'


from .models import Comment
  
class CommentForm(forms.ModelForm):
    content = forms.CharField(label ="", widget = forms.Textarea(
    attrs ={
        'class':'form-control',
        'placeholder':'Comment here !',
        'rows':4,
        'cols':50
    }))
    class Meta:
        model = Comment
        fields =['content']

tik/views.py
from urllib import response
from django.contrib import messages
from django.http import Http404, HttpResponse
from django.conf import settings
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm,LoginForm,PosteForm, DemanderForm, CommentForm
from django.contrib.auth.decorators import permission_required
from .models import Demandeur, Postes, User, Comment
from django.contrib.auth.models import Group
from django.http import FileResponse
import os





""""
def some_view(request):
    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()

    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(100, 100, "Hello world.")

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename='hello.pdf')

"""


def index(request):
    postes = Postes.objects.all()
    return render(request, 'tik/index.html', {'postes':postes})



def register(request):
    form = RegisterForm()
    if request.method=='POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name='hommes')
            group = Group.objects.get(name='femmes')
            user.groups.add(group)
            messages.success(request, " Compte creer ")
            return redirect(settings.LOGIN_REDIRECT_URL)
    return render(request, 'tik/register.html', {'form':form})




def login_us(request):
    forms = LoginForm()
    if request.method =='POST':
        forms = LoginForm(request.POST)
        if forms.is_valid():
            user = authenticate(request, username= forms.cleaned_data['username'], password= forms.cleaned_data['password'])
            if user is not None and user.is_homme:
                login(request, user)
                return redirect("homme")
                
            elif user is not None and user.is_femme:
                login(request, user)
                return redirect('femme')
    return render(request, 'tik/login.html', {'forms':forms})






def upload(request):
    upload = PosteForm()
    if request.method =='POST':
        upload = PosteForm(request.POST)
        if upload.is_valid():
            upload.save()
            return redirect("index")

    return render(request, 'tik/upload_poste.html', {'upload':upload})


def detail_post(request, id):
    post = get_object_or_404(Postes, id=id)
    comments = Comment.objects.all()
    new_comment = None
    if request.method =='POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
           # NOUVEAU COMMENTAIRE EGALE A L OBJECT POST DE DATAIL
            new_comment.post = post
            new_comment.save()
    return render(request, 'tik/post_detail.html', {'post':post, 'comments':comments, 'new_comment':new_comment})



def editform(request, my_id):
    form = Postes.objects.get(id=my_id)
    upload = PosteForm(instance=form)
    if request.method=='POST':
        upload = PosteForm(request.POST, instance=form)
        if upload.is_valid():
            upload.save()
            return redirect('index')
    return render(request, 'tik/edit.html', {'upload':upload})




def demander(request):
    de = DemanderForm()
    if request.method =='POST':
        de = DemanderForm(request.POST)
        if de.is_valid():
            de.save()
            return redirect('staff')

    return render(request, 'tik/demander.html', {'de':de})




def staf(request):
    de = Demandeur.objects.all()
    return render(request, 'tik/staff.html',{'de':de})



def donne(request):
    return render(request, 'tik/donnees.html')




def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb')as fh:
            response=HttpResponse(fh.read(),content_type='tik/upload')
            response["content Disposition"]="inline;filename"+os.path.basename(file_path)
            return response
    raise Http404



def detail(request, id):
    de = get_object_or_404(Demandeur, id=id)
    return render(request, 'tik/donnees.html', {'de':de})




def updatedemande(request, id):
    dem = Demandeur.objects.get(id=id)
    de = DemanderForm(instance=dem)
    if request.method=='POST':
        de = DemanderForm(request.POST, instance=dem)
        if de.is_valid():
            de.sava()
            return redirect('donnee')
    return render(request, 'tik/updated.html', {'de':de})














def homme(request):
    return render(request, 'tik/homme.html')





def femme(request):
    return render(request, 'tik/femme.html')




def logout_user(request):
    logout(request)

tik/templates/tik/demander.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>juge</title>
</head>
<body>       
    <secton class="section">
    <div class="box">
    <div class="field">
        <form method="post">
        {% csrf_token %}
        <label class="label">Nom demandeur</label>
        <div class="control">
          <input class="input" type="text" name="nom_demandeure" placeholder="Text input">
        </div>

        <label class="label">Nom</label>
        <div class="control">
          <input class="input" type="text" name="nom" placeholder="Text input">
        </div>

        <label class="label">Local</label>
        <div class="control">
          <input class="input" type="text" name="local" placeholder="Local">
        </div>

        <label class="label">Nom du demandeur</label>
        <div class="control">
          <input class="input" type="text" name="nom_demandeur" placeholder="Nom du demandeur">
        </div>

        <label class="label">om avocat2</label>
        <div class="control">
          <input class="input" type="text" name="om avocat2" placeholder="om avocat 2">
        </div>

        <label class="label">om avocat2</label>
        <div class="control">
          <input class="input" type="text" name="nom avocat2" placeholder="om avocat 2">
        </div>

        <label class="label">Nom du notaire:</label>
        <div class="control">
          <input class="input" type="text" name="nom_notaire" placeholder="om avocat 2">
        </div>
        <label class="label">Date invitation:</label>
        <div class="control">
          <input class="input" type="text" name="date_invitation" placeholder="nom avocat 2">
        </div>
        <label class="label">Num invitation::</label>
        <div class="control">
          <input class="input" type="text" name="num_inivation" placeholder="nom avocat 2">
        </div>

        <label class="label">vehicul_type:</label>
        <div class="control">
          <input class="input" type="text" name="vehicul_type" placeholder="nom avocat 2">
        </div>


        <label class="label">matricule:</label>
        <div class="control">
          <input class="input" type="text" name="matricule" placeholder="nom avocat 2">
        </div>

        <label class="label">Date accident:</label>
        <div class="control">
          <input class="input" type="date" name="date_accident" placeholder="date_accident">
        </div>

        <label class="label">Lieu accident:</label>
        <div class="control">
          <input class="input" type="text" name="lieu_accident" placeholder="lieu_accident">
        </div>

        <label class="label">Nom proces:</label>
        <div class="control">
          <input class="input" type="text" name="nom_proces" placeholder="lieu_accident">
        </div>

        <label class="label">Date Pv:</label>
        <div class="control">
          <input class="input" type="text" name="date_pv" placeholder="lieu_accident">
        </div>

        <label class="label">Source Pv:</label>
        <div class="control">
          <input class="input" type="text" name="source_pv" placeholder="lieu_accident">
        </div>

        <label class="label">Description Accident:</label>
        <div class="control">
          <input class="input" type="text" name="description_acc" placeholder="lieu_accident">
        </div>

        <label class="label">Numero Ordonance:</label>
        <div class="control">
          <input class="input" type="text" name="num_ordonance" placeholder="lieu_accident">
        </div>

        <label class="label">Date Ordonance:</label>
        <div class="control">
          <input class="input" type="text" name="date_ordonance" placeholder="lieu_accident">
        </div>

        <label class="label">Type Verhicule:</label>
        <div class="control">
          <input class="input" type="text" name="type_vehicule" placeholder="lieu_accident">
        </div>
        

        
        <label class="label">Date Expertise:</label>
        <div class="control">
          <input class="input" type="text" name="date_expertise" placeholder="lieu_accident">
        </div>


        
        <label class="label">Dmg Materiel</label>
        <div class="control">
          <input class="input" type="text" name="dmg_materiel" placeholder="lieu_accident">
        </div>


        
        <label class="label">Numero du dossier:</label>
        <div class="control">
          <input class="input" type="text" name="numero_dossier" placeholder="lieu_accident">
        </div>


        
        <label class="label">Nom Avocat 1</label>
        <div class="control">
          <input class="input" type="text" name="nom_avocat1" placeholder="lieu_accident">
        </div>



        
        <label class="label">Nom avocat 2:</label>
        <div class="control">
          <input class="input" type="text" name="nom_avocat2" placeholder="lieu_accident">
        </div>



        
        <label class="label">Date Pleorie:</label>
        <div class="control">
          <input class="input" type="date" name="date_pledoirie" placeholder="lieu_accident">
        </div>

        <label class="label">Nom avocat:</label>
        <div class="control">
          <input class="input" type="text" name="type_vehicule" placeholder="lieu_accident">
        </div>
      </div>
   
      <div class="field">
        <label class="label">Message</label>
        <div class="control">
          <textarea class="textarea" placeholder="Textarea"></textarea>
        </div>
      </div>
      
      
      <div class="field is-grouped">
        <div class="control">
          <button class="button is-link" type="submit">Submit</button>
        </div>
        <div class="control">
          <button class="button is-link is-light" type="reset">Cancel</button>
        </div>
      </div>
      </div>
    </form>
      </secton>




      
</body>
</html>

tik/templates/tik/detail.html
{% for post in posts %}


<h2>{{posts.titre}}</h2>
<p>{{posts.desc}}</p>

{% endfor %}

tik/templates/tik/donnees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

    <title>Document</title>
</head>
<body>


<p>

    المدّعي :
{{des.nom}},المعين محل مخابرته بمكتب محاميه الاستاذ {{des.avocat}} والكائن مقره {{des.avocat}}.

</p>

<p>
    من جهة
والمدّعى عليها:
{{des.nom_demandeur}} في شخص ممثلها القانوني ينوبها الأستاذ {{des.nom_avocat2}} والكائن مقره{{des.local2}}.
من جهة ثانية

</p>

<p>

    بمقتضى عريضة الدعوى المقدّمة من نائب المدّعي مع ما يفيد دفع المعاليم القانونيّة والمبلّغة للمدّعى عليها بتاريخ {{des.date_invitation}} بواسطة عدل التنفيذ {{nom_notaire}} حسب رقيمه عدد {{num_invitation}}  المتضمّن استدعاءها للحضور بالجلسة المقرّر انعقادها يوم [date de la premiére cour] وذلك للنظر في الدعوى المرفوعة ضدّها والآتي بيان موضوعها.


</p>

<h1>مــــوضــــوع الــــــدعـــــــوى</h1>

<p>
    يعرض المدعي أن {{des.vehicule_type}} ذات الرقم المنجمي {{des.matricule}} والتابعة له تعرضت إلى حادث مرور في {{des.date_accident}} ب{{des.lieu_accident}}  مما هو ثابت من محضر البحث الجزائي عدد {{des.nom_proces}} الصادر في {{daes.date_pv}} من قبل {{des.source_pv}}
و حيث تتثمثل صورة الحادث في [description accident]
و حيث تم تكليف الخبير في الميكانيك {{des.nom_expert}} بمقتضى اذن على عريضة  {{des.num_ordonance}} بتاريخ {{des.date_ordonance}} و عاين الخبير المنتدب ال    {{des.type_vehicule}} في {{des.date_expertise}} منتهيا إلى كون الأضرار تقدر ب        {{des.dmg_materiel}}
لذا يطلب المدعي إلزام {{des.nom_demander}} بوصفها تحل محل معاقدها في الأداء بأن تؤدي له المبالغ التالية:

</p>

<h1>الإجـــــــــــــــــــــــــــــــــــراءات</h1>

<p>
    وبموجب ذلك رسمت القضيّة بالدفتر المعدّ لنوعها تحت عدد {{des.numero_dossier}} وتمّ نشرها بالجلسة المبيّن تاريخها بالاستدعاء وبها حضر الأستاذ {{des.nom_avocat1}} و تمسك وحضر الأستاذ {{des.nom_avocat2}}  وأعلن نيابته ثم تتالى نشر القضية بجلسات أخرى اقتضاها سيرها آخرها جلسة المرافعة المنعقدة يوم {{des.date_pledoirie}} وبها حضر الاستاذ {{des.nom_avocat1}} وحضر الاستاذ {{des.nom_avocat2}} وتمسكا.
إثر ذلك قرّرت المحكمة حجز القضيّة للمفاوضة والتّصريح بالحكم بجلسة الطّالع وبها وبعد الاطّلاع على أوراق القضيّة والمفاوضة طبق القانون صرّح علنا بالحكم الآتي بيانه سندا ونصّا	:

</p>

<h1>الـــــــمــــــــســـــــتــــــــنــــــــدات</h1>
<p>
    حيث تهدف الدعوى إلى الحكم وفق الطلبات المضمّنة بعريضتها.
وحيث أدلى المدّعي تأييدا لدعواه ب:
1/ أصل رقيم الاستدعاء للجلسة.
2/ أصل إذن على عريضة.
3/ أصل محضر إعلام بإذن على عريضة.
4/ أصل تقرير اختبار.
5/ نسخة مطابقة للأصل من محضر بحث جزائي

</p>

<h1>الــــــــمـــــحـــكـــــمـــة</h1>

<h3>حيث تهدف الدعوى الى القضاء بإلزام المدعى عليها في شخص ممثلها القانوني بأن تؤدي للمدعي المبالغ التالية :</h3>

<p>
    {{des.dmg_materiel}}  لقاء الأضرار اللاحقة بالسيارة
[cout expertise] مصاريف اختبار
 [honoraire avovat demandés] لقاء أتعاب تقاضي و  أجرة محاماة
 [cout invitaion] لقاء محضر استدعاء للجلسة
[honoraire avocat ordonnance demandés] أجرة محاماة في اذن على عريضة 
[cout invitation expertise] أجرة استدعاء لاجراء عملية اختبار وحمل المصاريف القانونية على المحكوم عليها.

</p>


<p>
    وحيث تعرضت ال{{des.type_vehicule}} التابعة للطالبة إلى حادث مرور بتاريخ         {{des.date_accident}} تمثل في  [description accident]و المؤمنة لدى المطلوبة.

</p>


<p>
    وحيث ما تجدر الإشارة إليه في البداية وان مناط هذه الدعوى هو القانون عدد 86 لسنة 2005 المؤرخ في 15-8-2005 الذي اقتضى في الفقرة الخامسة من الفصل 121 انه:  "...لا تنطبق أحكام هذا الباب على الأضرار المادية التي تلحق العربة البرية ذات محرك"  على إلا أن ذلك الإقصاء كان من مجال الباب الثاني من القانون عدد 86 لسنة 2005  وعليه فاستبعاد المشرع لانطباق أحكام الباب الثاني من نفس القانون على الأضرار المادية اللاحقة بالعربات كان في طريقة تحديد التعويض دون المساس بالمسؤولية التي تبقى خاضعة للمقاييس المبينة بجدول تحديد المسؤوليات الملحق بالقانون والمنصوص عليه بالفصل 123 من نفس القانون .

</p>

<p>
    وحيث يتأكد ذلك من أحكام الفقرة الأخيرة من الفصل 121من م  التامين إذ ورد بها :" "وتعوض تلك الأضرار حسب نسبة المسؤولية غير المحمولة على السائق سواء كانت العربة على ملكه أو على ملك غيره " وانه حسب الوضع اللغوي فان عبارة " تلك الأضرار " تعود على الأضرار المادية للعربة إذ أضاف المشرع بالفقرة الأخيرة " سواء كانت العربة على ملكه  أو على ملك غيره " فعبارة العربة لم ترد بالفصل 121 إلا في الفقرتين الخامسة والسادسة  وهو تأكيد يرمي من ورائه المشرع إلى تكريس مبدأ التعويض عن الأضرار حسب نسبة المسؤولية سواء كان مالكها هو السائق أو غيره وما كان المشرع ليلجأ لهذا لو كان الأمر يتعلق بالأضرار البدنية فقط.

</p>


<p>
    وحيث أن التنصيص بالفقرة الخامسة من الفصل 121 من م التامين على عدم انطباق أحكام هذا الباب على الأضرار المادية يجب أن يفهم بضميمة الفقرة السادسة من الفصل المذكور ذلك  أن قانون 2005 أرسى نظام المسؤولية الموضوعية لتعويض الأضرار البدنية  وان الاستثناء الوارد بالفقرة السادسة من الفصل 121 يعني استثناء للمسؤولية الموضوعية عند التعويض عن الضرر المادي اللاحق بالعربة فحققت الفقرة المذكورة أن التعويض يتم على أساس المسؤولية الشخصية المؤسسة على الخطأ وبذلك يتبين أن المشرع قد وضع نظاما قانونيا جديدا للتعويض عن الأضرار المادية للعربات يعتمد نسبة مسؤولية الأطراف المشاركة في الحادث . 

</p>


<p>
    وحيث انه والحالة ما ذكر فان البت في مسالة مدى مساهمة السائق في حصول الحادث وعليه تحمل تبعة فعله حسب نسبة المسؤولية المحمولة عليه بغية التوصل الى تعويض عادل يقتضي ضرورة  إعمال قاعدة الفصل 83 من م.ا.ع وعليه توزيع المسؤولية حسب الجدول الملحق بالفصل 123 من مجلة التامين.
و حيث ثبت من خلال من محضر بحث جزائي عدد {{des.num_pv}} بتاريخ [date P.V] عن {{des.source_pv}} الخطاء المنسوب في سائق الوسيلة المؤمنة لدى المطلوبة و المتمثل في [description faute] و بالتالي قيام مسؤولية هذا الأخير.

</p>

<p>
    وحيث اقتضى الفصل 83 منم.ا.ع أن:" من تسبب في مضرة غيره خطا سواء كانت المضرة حسية آو معنوية فهو مسؤول بخطئه إذا ثبت انه السبب الوحيد الموجب للمضرة مباشرة "
وحيث اقتضى الفصل 107 منم.ا.ع أن :" الخسارة الناشئة عن جنحة  أو شبهها تشمل ما تلف حقيقة لطالبها  وما صرفه أو لا بد أن يصرفه لتدارك عواقب الفعل المضر به  والأرباح المعتادة التي حرم منها  بسبب ذلك الفعل  وتقدير الخسارة  من المحكمة يختلف  باختلاف سبب الضرر  من كونه تغريرا  أو خطا "
و حيث أن الوسيلة المتسببة في الحادث مؤمنة لدى المطلوبة و تأمينها ساري المفعول من [periode d’assurance]

</p>

<p>
    وحيث انه وطالما ثبت وان العربة مؤمنة لدى المطلوبة فقد اتجه تبعا إلزامها بالتعويض  للمدعي وتحميلها كامل المسؤولية عن الحادث.
وحيث تم تكليف الخبير في الميكانيك {{des.nom_expert}} بمقتضى الاذن على العريضة عدد {{des.num_ordonance}}بتاريخ {{des.date_ordonance}}
و حيث عاين الخبير المنتدب السيارة محل القضية بتاريخ [date expertise] 
</p>

    
</body>
</html>

tik/templates/tik/edit.html
<h1>Hedit PAGE</h1>


<form method="post">
    {% csrf_token %}
    {{upload.as_p}}

    <input type="submit">
</form>

tik/templates/tik/femme.html
<h1>Page des femmes</h1>

<a href="{% url 'index' %}">Show to Home</a>

tik/templates/tik/homme.html
<h1>pAGE DES HOMMES</h1>

<a href="{% url 'index' %}">Show to Home</a>

tik/templates/tik/index.html
<h1>HOME PAGE</h1>

{{user}}


<a href="{% url 'login' %}">Login</a>
<br><br>
<a href="{% url 'register' %}">Register</a>
<br><br>
<a href="{% url 'logout' %}">Logout</a>
<br>
<br>
<a href="{% url 'demandeur' %}">Demandeur</a>
<br>
<a href="{% url 'staf' %}">Staff</a>
<br>



<br><br>
<a href="{% url 'upload' %}">upload</a>
<br><br>





<br><br>
{% if perms.tik.add_postes %}
<a href="#">delete</a>
{% endif %}
<br><br>
{% for poste in postes %}
{% if perms.tik.add_postes %}
<a href="{% url 'update' poste.id %}">Edit</a>
<a href="{% url 'post' poste.id %}">commente</a>


{% endif %}
<br><br>

<h2>{{poste.titre}}</h2>
<p>{{poste.desc}}</p>
{{poste.date_joind}}
{{poste.pub_date}}
<p>Créer par {{poste.autheur}}</p>



{% endfor %}

{% for comment in comments %}
<div class="comments" style="padding: 10px;">
  <p class="font-weight-bold">
    {{ comment.name }}
    <span class=" text-muted font-weight-normal">
      {{ comment.created_on }}
    </span>
  </p>
  {{ comment.body | linebreaks }}
</div>
{% endfor %}

tik/templates/tik/login.html
<h1>LOGIN</h1>

<form method="post">

    {% csrf_token %}

    {{forms.as_p}}

    <input type="submit">

</form>

tik/templates/tik/post_detail.html
{% for comment in comments %}
{{comment.content}}
{{comment.post.pub_date}}
{{comment.post.autheur}}






{% endfor %}
<form method="POST">
    {% csrf_token %}
    {{comment_form.as_p}}
        <input type="submit">
  </form>

tik/templates/tik/rap.html
<h1>rap</h1>

tik/templates/tik/register.html
<h1>REGISTER</h1>

{% for message in messages %}

{{message}}

{% endfor %}



<form method="post">
    {% csrf_token %}

    {{form.as_p}}

    <input type="submit">
</form>

tik/templates/tik/updated.html
<form method="post">
    {% csrf_token %}
    {{de.as_p}}
    <input type="submit">
</form>

tik/templates/tik/upload_poste.html
<form method="post">
    {% csrf_token %}

    {{upload.as_p}}

    <input type="submit">
</form>